import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Next JS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{marginBottom: '16px'}}>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href='/posts/first-post/'>
          <a className='text-2xl pt-0 p-2 rounded border-2'>Goto First Post</a>
        </Link>
      </main>

    </div>
  )
}
